version: 1.2
workflows:

  - name: ImputationBeagle
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation_beagle/ImputationBeagle.wdl

  - name: CreateImputationRefPanelBeagle
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/arrays/imputation_beagle/CreateImputationRefPanelBeagle.wdl
